# идентификаторы установки
device_identifiers:
  id_device: a1
  hash_key: 8804b613
# конфигурация базы данных
db_config:
  host: 91.122.14.126
  database: technohub
  user: orangepi
  password: mariadb
# конфигурация сети modbus
modbus_config:
  self.device_name='d1'
  port_name='/dev/ttyUSB0'
  slave_address=100
  baud_rate=9600
  byte_size=8
  stop_bits=1
  time_out=0.1
  registeraddress = 0
  number_of_registers=7
  functioncode=4
