time_update:  1689255008 # время модификации в формате TIMESTEMP
name: Монитор качества воздуха
experiment_type: physical
description: Эксперимент позволяет регистрировать параметры воздуха в учебном помещении
tags: 
  - пуки
  - качество воздуха
  - углекислый газ
  - датчик
owner: OOO "Рога и копыта"
address: Санкт-Петербург, ул.Большая Морская, д.67
contacts: tel +7 (921) 588-57-37, email bznpavel@yandex.ru
service_options: # служебные параметры
  name: Служебные параметры установки
  values:
    max_initional_time:
      name: ограничение на время начальной инициализации установки
      dimension: сек.
      type: float
      value: 10
    max_reserved_claims:
      name: ограничение на количество заявок при слепом резервировании
      dimension: шт.
      type: integer
      value: 3
full_description: >-
                  Особенности задачи остабилизации перевернутого маятника  
                  можно посмотреть по ссылке [Текст ссылки](https://www.example.com).
                  You can even add equation numbers (unfortunately there is no
                  automatic numbering and refs support)
                  $$|\vec{A}|=\sqrt{A_x^2 + A_y^2 + A_z^2}.$$(1)
