time_update: 1689677509 # время модификации в формате TIMESTEMP
time_options: # временные параметры эксперимента
  name: Временные параметры
  values: 
    start_time:
      ws_name: начальное значение времени
      ws_dimension: сек
      ws_type: integer
      ws_regexp: ^([1-9]|10)$
      ws_value: целое число 1 от до 10
      ws_control: field
    delta_time:
      ws_name: время дискретизации
      ws_dimension: сек
      ws_type: float
      ws_regexp: null
      ws_value: 0.1
      ws_control: readonly
    scale_time:
      ws_name: масштаб времени
      ws_dimension: б/р
      ws_type: float
      ws_regexp: null
      ws_value: 1
      ws_control: readonly    
initial state: # контролируемые параметры начального состояния
  name: Начальное состояние
  values:
    back_light:
      ws_name: интенсивность подсветки
      ws_dimension: состояние
      ws_type: integer 
      ws_regexp: ^(нет|слабо|сильно)$
      ws_value: нет, слабо или сильно
      ws_dictionary: {нет: 0, слабо: 1, сильно: 2}
      ws_control: switch
      mb_reg_name: holding # input, holding
      mb_reg_address: 16
      mb_reg_type: uint16_t
      mb_decimals: 0 # если число то это степень 1/10 при чтении и 10 при записи
model_parameters: # параметры модели
  name: Параметры модели
  values:
    mute_state:
      ws_name: звуковая сигнализация
      ws_dimension: состояние
      ws_type: integer
      ws_regexp: ^(выкл|вкл)$
      ws_value: выкл или вкл
      ws_control: switch
      mb_dictionary: {выкл: 0, вкл: 1}
      mb_reg_name: holding
      mb_reg_address: 17
      mb_reg_type: bit
      mb_decimals: 0 # если бит то это сдвиг 
    temperature_unit:
      ws_name: размерность температуры
      ws_dimension: код
      ws_type: integer
      ws_regexp: ^[F,C]$
      ws_value: F или C
      ws_dictionary: {C: 0, F: 1}
      ws_control: switch
      mb_reg_name: holding # input, holding
      mb_reg_address: 17
      mb_reg_type: bit
      mb_decimals: 1
influences: # параметры входных воздействий
  name: Параметры внешней среды
  values:
    air_flow:
      ws_name: величина потока воздуха
      ws_dimension: куб.м в сек.
      ws_type: string
      ws_regexp: null
      ws_value: 0
      ws_control: readonly
      mb_reg_name: null # input, holding
      mb_reg_address: null
      mb_reg_type: null
      mb_decimals: 0
comments: # комментарий к эксперименту
  name: Комментарии к эксперименту
  values:
    comment:
      ws_name: Комментарий
      ws_regexp: ^(?!.*краткий\sкомментарий).*
      ws_value: краткий комментарий
      ws_control: field
      ws_dimension:
